Write a proper test setup

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -19,11 +19,20 @@ jobs:
       - name: Run from main.js
         id: tag_dev
         run: |
-          GITHUB_REF= node main.js #&& false || true
-          GITHUB_REF=origin/refs/tag/v1 node main.js #&& false || true
-          GITHUB_REF=refs/tag/v1 node main.js #&& false || true
-          GITHUB_REF=refs/heads/main node main.js #&& false || true
+          GITHUB_REF="" node main.js 
+          if [ $? -ne 1 ]; then echo "Expected failure on no GITHUB_REF set"; fi
+
+          GITHUB_REF=origin/refs/tag/v1 node main.js
+          if [ $? -ne 1 ]; then echo "Expected failure on invalid ref"; fi
+
+          GITHUB_REF=refs/tag/v1 node main.js
+          if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref to tag"; fi
+
+          GITHUB_REF=refs/heads/main node main.js
+          if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref to branch"; fi
+
           GITHUB_REF=refs/tags/v1.0.0 node main.js
+          if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref with minor version"; fi
           
       - name: Test dev
         run: |
