Fixing actionlint issues (#44)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,16 +20,25 @@ jobs:
     - name: Run dev
       id: tag_dev
       run: |
-        GITHUB_REF=node main.js && false || true
-        echo "1. GITHUB_REF"
-        GITHUB_REF=origin/refs/tag/v1 node main.js && false || true
-        echo "2. GITHUB_REF"
-        GITHUB_REF=refs/tag/v1 node main.js && false || true
-        echo "3. GITHUB_REF"
-        GITHUB_REF=refs/heads/main node main.js && false || true
-        echo "4. GITHUB_REF"
+        GITHUB_REF="" node main.js
+        # shellcheck disable=SC2181
+        if [ $? -ne 1 ]; then echo "Expected failure on no GITHUB_REF set"; fi
+
+        GITHUB_REF=origin/refs/tag/v1 node main.js
+        # shellcheck disable=SC2181
+        if [ $? -ne 1 ]; then echo "Expected failure on invalid ref"; fi
+
+        GITHUB_REF=refs/tag/v1 node main.js
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref to tag"; fi
+
+        GITHUB_REF=refs/heads/main node main.js
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref to branch"; fi
+
         GITHUB_REF=refs/tags/v1.0.0 node main.js
-        echo "5. GITHUB_REF"
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then echo "Not expected a failure on valid ref with minor version"; fi
         
     - name: Test dev
       run: |
